### ISSUE TITLE
Can not work with newer pytest (2.9.1)

### ISSUE THREAD

**Issue by georgexsh** [klrmn/pytest-random#10]
with error message: "py.test: error: unrecognized arguments: --random", seems pytest plugin interface has changed.

**Comment by klrmn** [comment]
two dashes instead of one? maybe the two dashes got translated to an emdash
somewhere along the way?

**Comment by georgexsh** [comment]
@klrmn thanks for your reply and sorry for the misleading message, it was `--random`.
I found a workable workaround by loading plugin explicitly: `-p random_plugin --random`, maybe there are something wrong with py.test plugin discovery mechanism.

**Comment by georgexsh** [comment]
after upgrade setuptools and virtualenv, this issue disappeared.
