### ISSUE TITLE
Release 0.02 on PyPI

### ISSUE THREAD

**Issue by 5long** [klrmn/pytest-random#3]
Hi, is there any reason that version 0.02 is tagged on Github but not released on PyPI? It'd be a lot easier just to use `pip install -U pytest-random` instead of using git URL.` One of the reasons I prefer py.test to nosetests is that I can't install [nose-randomize](https://github.com/my8bird/nose-randomize) and [nose-machineout](https://github.com/nvie/nose-machineout) from PyPI.

**Comment by klrmn** [comment]
@5long, Thanks for pointing out I hadn't done that. You should find it on pypi now. Happy testing.
